#ifndef CSSOM_CSS_FONT_FACE_RULE_H
#define CSSOM_CSS_FONT_FACE_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSFontFaceRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif






CSSOM_CSSStyleDeclaration* CSSOM_CSSFontFaceRule_style(const CSSOM_CSSFontFaceRule * cssFontFaceRule);



#ifdef __cplusplus
}
#endif

#endif
