#ifndef CSSOM_CSS_IMPORT_RULE_H
#define CSSOM_CSS_IMPORT_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSImportRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif






const char * CSSOM_CSSImportRule_href(const CSSOM_CSSImportRule * cssImportRule);



#ifdef __cplusplus
}
#endif

#endif
