#ifndef CSSOM_CSS_MEDIA_RULE_H
#define CSSOM_CSS_MEDIA_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSMediaRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif






#ifdef __cplusplus
}
#endif

#endif
