#ifndef CSSOM_CSS_MEDIA_RULE_H
#define CSSOM_CSS_MEDIA_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>
#include <cssom/CSSRuleList.h>

#ifdef __cplusplus
extern "C" {
#endif



#define CSSOM_CSSMediaRule_acquire(cssMediaRule) \
  CSSOM_CSSRule_acquire((CSSOM_CSSRule*)(cssMediaRule))



#define CSSOM_CSSMediaRule_release(cssMediaRule) \
  CSSOM_CSSRule_release((CSSOM_CSSRule*)(cssMediaRule))



CSSOM_MediaList* CSSOM_CSSMediaRule_media(const CSSOM_CSSMediaRule * cssMediaRule);



void CSSOM_CSSMediaRule_setMedia(CSSOM_CSSMediaRule * cssMediaRule, const char * media);



CSSOM_CSSRuleList* CSSOM_CSSMediaRule_cssRules(const CSSOM_CSSMediaRule * cssMediaRule);



unsigned long CSSOM_CSSMediaRule_insertRule(CSSOM_CSSMediaRule * cssMediaRule, const char * rule, unsigned long index);



void CSSOM_CSSMediaRule_deleteRule(CSSOM_CSSMediaRule * cssMediaRule, unsigned long index);



#ifdef __cplusplus
}
#endif

#endif
