#ifndef CSSOM_CSS_NAMESPACE_RULE_H
#define CSSOM_CSS_NAMESPACE_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef struct _CSSOM_CSSNamespaceRule CSSOM_CSSNamespaceRule;



#define CSSOM_CSSNamespaceRule_acquire(cssNamespaceRule) \
  CSSOM_CSSRule_acquire((CSSOM_CSSRule*)(cssNamespaceRule))



#define CSSOM_CSSNamespaceRule_release(cssNamespaceRule) \
  CSSOM_CSSRule_release((CSSOM_CSSRule*)(cssNamespaceRule))



#ifdef __cplusplus
}
#endif

#endif
