#ifndef CSSOM_CSS_NAMESPACE_RULE_H
#define CSSOM_CSS_NAMESPACE_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif






const char * CSSOM_CSSNamespaceRule_namespaceURI(const CSSOM_CSSNamespaceRule * cssNamespaceRule);



const char * CSSOM_CSSNamespaceRule_prefix(const CSSOM_CSSNamespaceRule * cssNamespaceRule);



#ifdef __cplusplus
}
#endif

#endif
