#ifndef CSSOM_CSS_NAMESPACE_RULE_H
#define CSSOM_CSS_NAMESPACE_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif



#define CSSOM_CSSNamespaceRule_acquire(cssNamespaceRule) \
  CSSOM_CSSRule_acquire((CSSOM_CSSRule*)(cssNamespaceRule))



#define CSSOM_CSSNamespaceRule_release(cssNamespaceRule) \
  CSSOM_CSSRule_release((CSSOM_CSSRule*)(cssNamespaceRule))



const char * CSSOM_CSSNamespaceRule_namespaceURI(const CSSOM_CSSNamespaceRule * cssNamespaceRule);



const char * CSSOM_CSSNamespaceRule_prefix(const CSSOM_CSSNamespaceRule * cssNamespaceRule);



#ifdef __cplusplus
}
#endif

#endif
