#ifndef CSSOM_CSS_PROPERTY_VALUE_H
#define CSSOM_CSS_PROPERTY_VALUE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSPropertyValue.idl'
 */



#include <cssom/typedefs.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_CSSPropertyValue_acquire(
  CSSOM_CSSPropertyValue * cssPropertyValue);



void CSSOM_CSSPropertyValue_release(
  CSSOM_CSSPropertyValue * cssPropertyValue);



const char * CSSOM_CSSPropertyValue_cssText(const CSSOM_CSSPropertyValue * cssPropertyValue);



#ifdef __cplusplus
}
#endif

#endif
