#ifndef CSSOM_CSS_PAGE_RULE_H
#define CSSOM_CSS_PAGE_RULE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSPageRule.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRule.h>

#ifdef __cplusplus
extern "C" {
#endif



#define CSSOM_CSSPageRule_acquire(cssPageRule) \
  CSSOM_CSSRule_acquire((CSSOM_CSSRule*)(cssPageRule))



#define CSSOM_CSSPageRule_release(cssPageRule) \
  CSSOM_CSSRule_release((CSSOM_CSSRule*)(cssPageRule))



const char * CSSOM_CSSPageRule_selectorText(const CSSOM_CSSPageRule * cssPageRule);



CSSOM_CSSStyleDeclaration* CSSOM_CSSPageRule_style(const CSSOM_CSSPageRule * cssPageRule);



#ifdef __cplusplus
}
#endif

#endif
