#ifndef CSSOM_CSS_RULE_LIST_H
#define CSSOM_CSS_RULE_LIST_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRuleList.idl'
 */



#include <cssom/CSSRule.h>
#include <cssom/Sequence.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef CSSOM_Sequence CSSOM_CSSRuleList;



#define CSSOM_CSSRuleList_size(cssRuleList) \
  (CSSOM_Sequence_size((cssRuleList)))



#define CSSOM_CSSRuleList_at(cssRuleList, index) \
  ((CSSOM_CSSRule*)CSSOM_Sequence_at((cssRuleList), (index)))



#ifdef __cplusplus
}
#endif

#endif
