#ifndef CSSOM_CSS_RULE_LIST_H
#define CSSOM_CSS_RULE_LIST_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRuleList.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/Sequence.h>

#ifdef __cplusplus
extern "C" {
#endif



#define CSSOM_CSSRuleList_acquire(cssRuleList) \
  (CSSOM_Sequence_acquire((cssRuleList)))



#define CSSOM_CSSRuleList_release(cssRuleList, index) \
  (CSSOM_Sequence_release((cssRuleList)))



#define CSSOM_CSSRuleList_length(cssRuleList) \
  (CSSOM_Sequence_length((cssRuleList)))



#define CSSOM_CSSRuleList_at(cssRuleList, index) \
  ((CSSOM_CSSRule*)CSSOM_Sequence_at((cssRuleList), (index)))



#ifdef __cplusplus
}
#endif

#endif
