#ifndef CSSOM_CSS_STYLE_SHEET_H
#define CSSOM_CSS_STYLE_SHEET_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleSheet.idl'
 */



#include <cssom/typedefs.h>

#include <cssom/CSSRuleList.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_CSSStyleSheet_acquire(
  CSSOM_CSSStyleSheet * cssStyleSheet);



void CSSOM_CSSStyleSheet_release(
  CSSOM_CSSStyleSheet * cssStyleSheet);



CSSOM_CSSRuleList* CSSOM_CSSStyleSheet_cssRules(const CSSOM_CSSStyleSheet * cssStyleSheet);



unsigned long CSSOM_CSSStyleSheet_insertRule(CSSOM_CSSStyleSheet * cssStyleSheet, const char * rule, unsigned long index);



void CSSOM_CSSStyleSheet_deleteRule(CSSOM_CSSStyleSheet * cssStyleSheet, unsigned long index);



#ifdef __cplusplus
}
#endif

#endif
