#ifndef CSSOM_CSS_STYLE_DECLARATION_H
#define CSSOM_CSS_STYLE_DECLARATION_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclaration.idl'
 */



#include <cssom/typedefs.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_CSSStyleDeclaration_acquire(
  CSSOM_CSSStyleDeclaration * cssStyleDeclaration);



void CSSOM_CSSStyleDeclaration_release(
  CSSOM_CSSStyleDeclaration * cssStyleDeclaration);



const char * CSSOM_CSSStyleDeclaration_cssText(const CSSOM_CSSStyleDeclaration * cssStyleDeclaration);



unsigned long CSSOM_CSSStyleDeclaration_length(const CSSOM_CSSStyleDeclaration * cssStyleDeclaration);



const char * CSSOM_CSSStyleDeclaration_getPropertyValue(const CSSOM_CSSStyleDeclaration * cssStyleDeclaration, const char * property);



const char * CSSOM_CSSStyleDeclaration_getPropertyPriority(const CSSOM_CSSStyleDeclaration * cssStyleDeclaration, const char * property);



CSSOM_CSSRule* CSSOM_CSSStyleDeclaration_parentRule(const CSSOM_CSSStyleDeclaration * cssStyleDeclaration);



#ifdef __cplusplus
}
#endif

#endif
