#ifndef CSSOM_CSS_STYLE_DECLARATION_VALUE_H
#define CSSOM_CSS_STYLE_DECLARATION_VALUE_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclarationValue.idl'
 */



#include <cssom/typedefs.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_CSSStyleDeclarationValue_acquire(
  CSSOM_CSSStyleDeclarationValue * cssStyleDeclarationValue);



void CSSOM_CSSStyleDeclarationValue_release(
  CSSOM_CSSStyleDeclarationValue * cssStyleDeclarationValue);



#ifdef __cplusplus
}
#endif

#endif
