#ifndef CSSOM_MEDIA_LIST_H
#define CSSOM_MEDIA_LIST_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSMediaRule.idl'
 */



#include <cssom/typedefs.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_MediaList_acquire(
  CSSOM_MediaList * mediaList);



void CSSOM_MediaList_release(
  CSSOM_MediaList * mediaList);



const char * CSSOM_MediaList_mediaText(const CSSOM_MediaList * mediaList);



void CSSOM_MediaList_setMediaText(CSSOM_MediaList * mediaList, const char * mediaText);



unsigned long CSSOM_MediaList_length(const CSSOM_MediaList * mediaList);



const char * CSSOM_MediaList_item(const CSSOM_MediaList * mediaList, unsigned long index);



#ifdef __cplusplus
}
#endif

#endif
