#ifndef CSSOM__MEDIA_LIST_H
#define CSSOM__MEDIA_LIST_H



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'MediaList.idl'
 */



#include <cssom/typedefs.h>

#ifdef __cplusplus
extern "C" {
#endif



void CSSOM_MediaList_acquire(
  CSSOM_MediaList * MediaList);



void CSSOM_MediaList_release(
  CSSOM_MediaList * MediaList);



#ifdef __cplusplus
}
#endif

#endif
