#include <cssompp/CSSFontFaceRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/CSSFontFaceRule.h>

#include <cssompp/CSSStyleDeclaration.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSFontFaceRule CSSFontFaceRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSFontFaceRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSFontFaceRule &>(cssRule);
}



CSSFontFaceRule & CSSFontFaceRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSFontFaceRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSFontFaceRule &>(cssRule);
}



CSSFontFaceRule::CSSFontFaceRule() :
  CSSRule()
{}



CSSFontFaceRule::CSSFontFaceRule(cssom::CSSFontFaceRule::Impl impl) :
  CSSRule((cssom::CSSRule::Impl)impl)
{}



cssom::CSSStyleDeclaration CSSFontFaceRule::style() const {
  return cssom::CSSStyleDeclaration(CSSOM_CSSFontFaceRule_style(reinterpret_cast<cssom::CSSFontFaceRule::Impl>(_impl)));
}



} // cssom
