#include <cssompp/CSSImportRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSImportRule.idl'
 */



#include <cssom/CSSImportRule.h>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSImportRule CSSImportRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSImportRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSImportRule &>(cssRule);
}



CSSImportRule & CSSImportRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSImportRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSImportRule &>(cssRule);
}



CSSImportRule::CSSImportRule() :
  CSSRule()
{}



CSSImportRule::CSSImportRule(CSSOM_CSSImportRule * impl) :
  CSSRule((CSSOM_CSSRule *)impl)
{}



const char * CSSImportRule::href() const {
  return CSSOM_CSSImportRule_href(reinterpret_cast<CSSOM_CSSImportRule*>(_impl));
}



} // cssom
