#include <cssompp/CSSImportRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/CSSImportRule.h>

#include <cssompp/MediaList.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSImportRule CSSImportRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSImportRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSImportRule &>(cssRule);
}



CSSImportRule & CSSImportRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSImportRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSImportRule &>(cssRule);
}



CSSImportRule::CSSImportRule() :
  CSSRule()
{}



CSSImportRule::CSSImportRule(cssom::CSSImportRule::Impl impl) :
  CSSRule((cssom::CSSRule::Impl)impl)
{}



const char * CSSImportRule::href() const {
  return CSSOM_CSSImportRule_href(reinterpret_cast<cssom::CSSImportRule::Impl>(_impl));
}



cssom::MediaList CSSImportRule::media() const {
  return cssom::MediaList(CSSOM_CSSImportRule_media(reinterpret_cast<cssom::CSSImportRule::Impl>(_impl)));
}



void CSSImportRule::setMedia(const char * media) {
  CSSOM_CSSImportRule_setMedia(reinterpret_cast<cssom::CSSImportRule::Impl>(_impl), media);
}



} // cssom
