#include <cssompp/CSSMediaRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/CSSMediaRule.h>

#include <cssompp/MediaList.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSMediaRule CSSMediaRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSMediaRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSMediaRule &>(cssRule);
}



CSSMediaRule & CSSMediaRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSMediaRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSMediaRule &>(cssRule);
}



CSSMediaRule::CSSMediaRule() :
  CSSRule()
{}



CSSMediaRule::CSSMediaRule(cssom::CSSMediaRule::Impl impl) :
  CSSRule((cssom::CSSRule::Impl)impl)
{}



cssom::MediaList CSSMediaRule::media() const {
  return cssom::MediaList(CSSOM_CSSMediaRule_media(reinterpret_cast<cssom::CSSMediaRule::Impl>(_impl)));
}



void CSSMediaRule::setMedia(const char * media) {
  CSSOM_CSSMediaRule_setMedia(reinterpret_cast<cssom::CSSMediaRule::Impl>(_impl), media);
}



cssom::CSSRuleList CSSMediaRule::cssRules() const {
  return cssom::CSSRuleList(CSSOM_CSSMediaRule_cssRules(reinterpret_cast<cssom::CSSMediaRule::Impl>(_impl)));
}



unsigned long CSSMediaRule::insertRule(const char * rule, unsigned long index) {
  return CSSOM_CSSMediaRule_insertRule(reinterpret_cast<cssom::CSSMediaRule::Impl>(_impl), rule, index);
}



void CSSMediaRule::deleteRule(unsigned long index) {
  return CSSOM_CSSMediaRule_deleteRule(reinterpret_cast<cssom::CSSMediaRule::Impl>(_impl), index);
}



} // cssom
