#include <cssompp/CSSNamespaceRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include "src/CSSNamespaceRule.h"

#include <utility>

namespace cssom {



} // cssom
