#include <cssompp/CSSNamespaceRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include <cssom/CSSNamespaceRule.h>

#include <utility>

namespace cssom {



CSSNamespaceRule CSSNamespaceRule::cast(
  const cssom::CSSRule & cssRule)
{
  return static_cast<const cssom::CSSNamespaceRule &>(cssRule);
}



CSSNamespaceRule & CSSNamespaceRule::cast(
  cssom::CSSRule & cssRule)
{
  return static_cast<cssom::CSSNamespaceRule&>(cssRule);
}



CSSNamespaceRule::CSSNamespaceRule(CSSOM_CSSNamespaceRule * impl) :
  CSSRule((CSSOM_CSSRule *)impl)
{}



} // cssom
