#include <cssompp/CSSNamespaceRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/CSSNamespaceRule.h>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSNamespaceRule CSSNamespaceRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSNamespaceRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSNamespaceRule &>(cssRule);
}



CSSNamespaceRule & CSSNamespaceRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSNamespaceRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSNamespaceRule &>(cssRule);
}



CSSNamespaceRule::CSSNamespaceRule() :
  CSSRule()
{}



CSSNamespaceRule::CSSNamespaceRule(CSSOM_CSSNamespaceRule * impl) :
  CSSRule((CSSOM_CSSRule *)impl)
{}



const char * CSSNamespaceRule::namespaceURI() const {
  return CSSOM_CSSNamespaceRule_namespaceURI(reinterpret_cast<CSSOM_CSSNamespaceRule*>(_impl));
}



const char * CSSNamespaceRule::prefix() const {
  return CSSOM_CSSNamespaceRule_prefix(reinterpret_cast<CSSOM_CSSNamespaceRule*>(_impl));
}



} // cssom
