#include <cssompp/CSSStyleDeclaration.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclaration.idl'
 */



#include <cssom/CSSStyleDeclaration.h>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSStyleDeclaration::CSSStyleDeclaration() :
  _impl(NULL)
{}



bool CSSStyleDeclaration::operator==(
  const cssom::CSSStyleDeclaration &rhs) const
{
  return _impl == rhs._impl;
}



bool CSSStyleDeclaration::isNull() const {
  return _impl == NULL;
}



CSSStyleDeclaration::CSSStyleDeclaration(CSSOM_CSSStyleDeclaration * impl) :
  _impl(impl)
{}



const char * CSSStyleDeclaration::cssText() const {
  return CSSOM_CSSStyleDeclaration_cssText(_impl);
}



unsigned long CSSStyleDeclaration::length() const {
  return CSSOM_CSSStyleDeclaration_length(_impl);
}



const char * CSSStyleDeclaration::getPropertyValue(const char * property) {
  return CSSOM_CSSStyleDeclaration_getPropertyValue(_impl, property);
}



const char * CSSStyleDeclaration::getPropertyPriority(const char * property) {
  return CSSOM_CSSStyleDeclaration_getPropertyPriority(_impl, property);
}



} // cssom
