#include <cssompp/CSSStyleDeclarationValue.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclarationValue.idl'
 */



#include <cssom/CSSStyleDeclarationValue.h>

#include <cssompp/CSSPropertyValue.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSStyleDeclarationValue::CSSStyleDeclarationValue() :
  _impl(NULL)
{}



CSSStyleDeclarationValue::CSSStyleDeclarationValue(CSSOM_CSSStyleDeclarationValue * impl) :
  _impl(impl)
{
  CSSOM_CSSStyleDeclarationValue_acquire(_impl);
}



CSSStyleDeclarationValue::CSSStyleDeclarationValue(const cssom::CSSStyleDeclarationValue &copy) :
  _impl(copy._impl)
{
  CSSOM_CSSStyleDeclarationValue_acquire(_impl);
}



CSSStyleDeclarationValue::~CSSStyleDeclarationValue() {
  CSSOM_CSSStyleDeclarationValue_release(_impl);
}



cssom::CSSStyleDeclarationValue& CSSStyleDeclarationValue::operator=(
  const cssom::CSSStyleDeclarationValue &rhs)
{
  if (&rhs == this) return *this;

  cssom::CSSStyleDeclarationValue(rhs).swap(*this);

  return *this;
}



bool CSSStyleDeclarationValue::operator==(
  const cssom::CSSStyleDeclarationValue &rhs) const
{
  return _impl == rhs._impl;
}



bool CSSStyleDeclarationValue::isNull() const {
  return _impl == NULL;
}



void CSSStyleDeclarationValue::swap(cssom::CSSStyleDeclarationValue &rhs) {
  std::swap(_impl, rhs._impl);
}



unsigned long CSSStyleDeclarationValue::length() const {
  return CSSOM_CSSStyleDeclarationValue_length(_impl);
}



const char * CSSStyleDeclarationValue::item(unsigned long index) {
  return CSSOM_CSSStyleDeclarationValue_item(_impl, index);
}



cssom::CSSPropertyValue CSSStyleDeclarationValue::getProperty(const char * property) {
  return cssom::CSSPropertyValue(CSSOM_CSSStyleDeclarationValue_getProperty(_impl, property));
}



void CSSStyleDeclarationValue::setProperty(const char * property, const char * value) {
  return CSSOM_CSSStyleDeclarationValue_setProperty(_impl, property, value);
}



void CSSStyleDeclarationValue::setProperty(const char * property, const char * value, const char * priority) {
  return CSSOM_CSSStyleDeclarationValue_setPropertyEx(_impl, property, value, priority);
}



const char * CSSStyleDeclarationValue::removeProperty(const char * property) {
  return CSSOM_CSSStyleDeclarationValue_removeProperty(_impl, property);
}



} // cssom
