#include <cssompp/CSSStyleDeclaration.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclaration.idl'
 */



#include <cssom/CSSStyleDeclaration.h>

#include <cssompp/CSSRule.hpp>
#include <cssompp/CSSStyleDeclarationValue.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSStyleDeclaration::CSSStyleDeclaration() :
  _impl(NULL)
{}



CSSStyleDeclaration::CSSStyleDeclaration(CSSOM_CSSStyleDeclaration * impl) :
  _impl(impl)
{
  CSSOM_CSSStyleDeclaration_acquire(_impl);
}



CSSStyleDeclaration::CSSStyleDeclaration(const cssom::CSSStyleDeclaration &copy) :
  _impl(copy._impl)
{
  CSSOM_CSSStyleDeclaration_acquire(_impl);
}



CSSStyleDeclaration::~CSSStyleDeclaration() {
  CSSOM_CSSStyleDeclaration_release(_impl);
}



cssom::CSSStyleDeclaration& CSSStyleDeclaration::operator=(
  const cssom::CSSStyleDeclaration &rhs)
{
  if (&rhs == this) return *this;

  cssom::CSSStyleDeclaration(rhs).swap(*this);

  return *this;
}



bool CSSStyleDeclaration::operator==(
  const cssom::CSSStyleDeclaration &rhs) const
{
  return _impl == rhs._impl;
}



bool CSSStyleDeclaration::isNull() const {
  return _impl == NULL;
}



void CSSStyleDeclaration::swap(cssom::CSSStyleDeclaration &rhs) {
  std::swap(_impl, rhs._impl);
}



const char * CSSStyleDeclaration::cssText() const {
  return CSSOM_CSSStyleDeclaration_cssText(_impl);
}



unsigned long CSSStyleDeclaration::length() const {
  return CSSOM_CSSStyleDeclaration_length(_impl);
}



const char * CSSStyleDeclaration::item(unsigned long index) {
  return CSSOM_CSSStyleDeclaration_item(_impl, index);
}



const char * CSSStyleDeclaration::getPropertyValue(const char * property) {
  return CSSOM_CSSStyleDeclaration_getPropertyValue(_impl, property);
}



const char * CSSStyleDeclaration::getPropertyPriority(const char * property) {
  return CSSOM_CSSStyleDeclaration_getPropertyPriority(_impl, property);
}



void CSSStyleDeclaration::setProperty(const char * property, const char * value) {
  return CSSOM_CSSStyleDeclaration_setProperty(_impl, property, value);
}



void CSSStyleDeclaration::setProperty(const char * property, const char * value, const char * priority) {
  return CSSOM_CSSStyleDeclaration_setPropertyEx(_impl, property, value, priority);
}



void CSSStyleDeclaration::removeProperty(const char * property) {
  return CSSOM_CSSStyleDeclaration_removeProperty(_impl, property);
}



cssom::CSSStyleDeclarationValue CSSStyleDeclaration::values() const {
  return cssom::CSSStyleDeclarationValue(CSSOM_CSSStyleDeclaration_values(_impl));
}



cssom::CSSRule CSSStyleDeclaration::parentRule() const {
  return cssom::CSSRule(CSSOM_CSSStyleDeclaration_parentRule(_impl));
}



} // cssom
