#include <cssompp/CSSStyleRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleRule.idl'
 */



#include <cssom/CSSStyleRule.h>

#include <cssompp/CSSStyleDeclaration.hpp>

#include <utility>

namespace cssom {



CSSStyleRule CSSStyleRule::cast(
  const cssom::CSSRule & cssRule)
{
  return static_cast<const cssom::CSSStyleRule &>(cssRule);
}



CSSStyleRule & CSSStyleRule::cast(
  cssom::CSSRule & cssRule)
{
  return static_cast<cssom::CSSStyleRule&>(cssRule);
}



CSSStyleRule::CSSStyleRule(CSSOM_CSSStyleRule * impl) :
  CSSRule((CSSOM_CSSRule *)impl)
{}



const char * CSSStyleRule::selectorText() const {
  return CSSOM_CSSStyleRule_selectorText(reinterpret_cast<CSSOM_CSSStyleRule*>(_impl));
}



cssom::CSSStyleDeclaration CSSStyleRule::style() const {
  return cssom::CSSStyleDeclaration(CSSOM_CSSStyleRule_style(reinterpret_cast<CSSOM_CSSStyleRule*>(_impl)));
}



} // cssom
