#include <cssompp/CSSStyleRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleRule.idl'
 */



#include "src/CSSStyleRule.h"

#include <cssompp/CSSStyleDeclaration.hpp>

#include <utility>

namespace cssom {



const char * CSSStyleRule::selectorText() const {
  return CSSOM_CSSStyleRule_selectorText(reinterpret_cast<CSSOM_CSSStyleRule*>(_impl));
}



cssom::CSSStyleDeclaration CSSStyleRule::style() const {
  return cssom::CSSStyleDeclaration(CSSOM_CSSStyleRule_style(reinterpret_cast<CSSOM_CSSStyleRule*>(_impl)));
}



} // cssom
