#include <cssompp/CSSStyleRule.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/CSSStyleRule.h>

#include <cssompp/CSSStyleDeclaration.hpp>
#include <cssompp/Selector.hpp>

#include "checks.hpp"

#include <utility>

namespace cssom {



CSSStyleRule CSSStyleRule::cast(
  const cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSStyleRule>(cssRule);
#endif // NDEBUG
  return static_cast<const cssom::CSSStyleRule &>(cssRule);
}



CSSStyleRule & CSSStyleRule::cast(
  cssom::CSSRule & cssRule)
{
#ifndef NDEBUG
  cssom::checkCast<cssom::CSSRule, cssom::CSSStyleRule>(cssRule);
#endif // NDEBUG
  return static_cast<cssom::CSSStyleRule &>(cssRule);
}



CSSStyleRule::CSSStyleRule() :
  CSSRule()
{}



CSSStyleRule::CSSStyleRule(cssom::CSSStyleRule::Impl impl) :
  CSSRule((cssom::CSSRule::Impl)impl)
{}



cssom::Selector CSSStyleRule::selector() const {
  return cssom::Selector(CSSOM_CSSStyleRule_selector(reinterpret_cast<cssom::CSSStyleRule::Impl>(_impl)));
}



const char * CSSStyleRule::selectorText() const {
  return CSSOM_CSSStyleRule_selectorText(reinterpret_cast<cssom::CSSStyleRule::Impl>(_impl));
}



void CSSStyleRule::setSelectorText(const char * selectorText) {
  CSSOM_CSSStyleRule_setSelectorText(reinterpret_cast<cssom::CSSStyleRule::Impl>(_impl), selectorText);
}



cssom::CSSStyleDeclaration CSSStyleRule::style() const {
  return cssom::CSSStyleDeclaration(CSSOM_CSSStyleRule_style(reinterpret_cast<cssom::CSSStyleRule::Impl>(_impl)));
}



} // cssom
