#include <cssompp/MediaList.hpp>



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'MediaList.idl'
 */



#include <cssom/MediaList.h>

#include "checks.hpp"

#include <utility>

namespace cssom {



MediaList::MediaList() :
  _impl(NULL)
{}



MediaList::MediaList(CSSOM_MediaList * impl) :
  _impl(impl)
{
  CSSOM_MediaList_acquire(_impl);
}



MediaList::MediaList(const cssom::MediaList &copy) :
  _impl(copy._impl)
{
  CSSOM_MediaList_acquire(_impl);
}



MediaList::~MediaList() {
  CSSOM_MediaList_release(_impl);
}



cssom::MediaList& MediaList::operator=(
  const cssom::MediaList &rhs)
{
  if (&rhs == this) return *this;

  cssom::MediaList(rhs).swap(*this);

  return *this;
}



bool MediaList::operator==(
  const cssom::MediaList &rhs) const
{
  return _impl == rhs._impl;
}



bool MediaList::isNull() const {
  return _impl == NULL;
}



void MediaList::swap(cssom::MediaList &rhs) {
  std::swap(_impl, rhs._impl);
}



} // cssom
