interface CSSStyleDeclarationValue {
  readonly attribute unsigned long length;
  DOMString item(unsigned long index);

  CSSPropertyValue? getProperty(DOMString property);
  void setProperty(DOMString? property, DOMString? value);
  void setProperty(DOMString? property, DOMString? value, DOMString? priority);
  void removeProperty(DOMString property);
};
