#ifndef CSSOMPP_CSS_IMPORT_RULE_HPP
#define CSSOMPP_CSS_IMPORT_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/typedefs.h>

namespace cssom {



class MediaList;



} // cssom

namespace cssom {



class CSSImportRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSImportRule * Impl;

    static cssom::CSSImportRule cast(const cssom::CSSRule & cssRule);
    static cssom::CSSImportRule & cast(cssom::CSSRule & cssRule);

    CSSImportRule();
    explicit CSSImportRule(cssom::CSSImportRule::Impl impl);

    const char * href() const;

    cssom::MediaList media() const;

    void setMedia(const char * media);
};



} // cssom

#endif // CSSOMPP_CSS_IMPORT_RULE_HPP
