#ifndef CSSOMPP_CSS_MEDIA_RULE_HPP
#define CSSOMPP_CSS_MEDIA_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSMediaRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/typedefs.h>


namespace cssom {



class CSSMediaRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSMediaRule * C;

    static cssom::CSSMediaRule cast(const cssom::CSSRule & cssRule);
    static cssom::CSSMediaRule & cast(cssom::CSSRule & cssRule);

    CSSMediaRule();
    explicit CSSMediaRule(CSSOM_CSSMediaRule * impl);
};



} // cssom

#endif // CSSOMPP_CSS_MEDIA_RULE_HPP
