#ifndef CSSOMPP_CSS_NAMESPACE_RULE_HPP
#define CSSOMPP_CSS_NAMESPACE_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/CSSNamespaceRule.h>


namespace cssom {



class CSSNamespaceRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSNamespaceRule * C;

};



} // cssom

#endif // CSSOMPP_CSS_NAMESPACE_RULE_HPP
