#ifndef CSSOMPP_CSS_NAMESPACE_RULE_HPP
#define CSSOMPP_CSS_NAMESPACE_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSNamespaceRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/CSSNamespaceRule.h>


namespace cssom {



class CSSNamespaceRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSNamespaceRule * C;

    static cssom::CSSNamespaceRule cast(const cssom::CSSRule & cssRule);
    static cssom::CSSNamespaceRule & cast(cssom::CSSRule & cssRule);

    explicit CSSNamespaceRule(CSSOM_CSSNamespaceRule * impl);
};



} // cssom

#endif // CSSOMPP_CSS_NAMESPACE_RULE_HPP
