#ifndef CSSOMPP_CSS_PAGE_RULE_HPP
#define CSSOMPP_CSS_PAGE_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/typedefs.h>

namespace cssom {



class CSSStyleDeclaration;



class Selector;



} // cssom

namespace cssom {



class CSSPageRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSPageRule * Impl;

    static cssom::CSSPageRule cast(const cssom::CSSRule & cssRule);
    static cssom::CSSPageRule & cast(cssom::CSSRule & cssRule);

    CSSPageRule();
    explicit CSSPageRule(cssom::CSSPageRule::Impl impl);

    cssom::Selector selector() const;

    const char * selectorText() const;
    void setSelectorText(const char * selectorText);

    cssom::CSSStyleDeclaration style() const;
};



} // cssom

#endif // CSSOMPP_CSS_PAGE_RULE_HPP
