#ifndef CSSOMPP_CSS_PROPERTY_VALUE_HPP
#define CSSOMPP_CSS_PROPERTY_VALUE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSPropertyValue.idl'
 */



#include <cssom/typedefs.h>


namespace cssom {



class CSSPropertyValue {
  public:
    typedef CSSOM_CSSPropertyValue * Impl;

    CSSPropertyValue();
    explicit CSSPropertyValue(cssom::CSSPropertyValue::Impl impl);
    CSSPropertyValue(const cssom::CSSPropertyValue &copy);
    ~CSSPropertyValue();

    cssom::CSSPropertyValue& operator=(const cssom::CSSPropertyValue &rhs);

    bool operator==(const cssom::CSSPropertyValue &rhs) const;

    bool isNull() const;

    void swap(cssom::CSSPropertyValue &rhs);

    const char * cssText() const;
    void setCSSText(const char * cssText);

  protected:
    cssom::CSSPropertyValue::Impl _impl;
};



} // cssom

#endif // CSSOMPP_CSS_PROPERTY_VALUE_HPP
