#ifndef CSSOMPP_CSS_PAGE_RULE_HPP
#define CSSOMPP_CSS_PAGE_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSPageRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/typedefs.h>

namespace cssom {



class CSSStyleDeclaration;



} // cssom

namespace cssom {



class CSSPageRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSPageRule * C;

    static cssom::CSSPageRule cast(const cssom::CSSRule & cssRule);
    static cssom::CSSPageRule & cast(cssom::CSSRule & cssRule);

    CSSPageRule();
    explicit CSSPageRule(CSSOM_CSSPageRule * impl);

    const char * selectorText() const;

    cssom::CSSStyleDeclaration style() const;
};



} // cssom

#endif // CSSOMPP_CSS_PAGE_RULE_HPP
