#ifndef CSSOMPP_CSS_RULE_LIST_HPP
#define CSSOMPP_CSS_RULE_LIST_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRuleList.idl'
 */



#include <cssompp/Sequence.hpp>

#include <cssom/CSSRuleList.h>

namespace cssom {



class CSSRule;



} // cssom

namespace cssom {



typedef cssom::Sequence<cssom::CSSRule> CSSRuleList;



} // cssom

#endif // CSSOMPP_CSS_RULE_LIST_HPP
