#ifndef CSSOMPP_CSS_STYLE_RULE_HPP
#define CSSOMPP_CSS_STYLE_RULE_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleRule.idl'
 */



#include <cssompp/CSSRule.hpp>

#include <cssom/CSSStyleRule.h>

namespace cssom {



class CSSStyleDeclaration;



} // cssom

namespace cssom {



class CSSStyleRule : public cssom::CSSRule {
  public:
    typedef CSSOM_CSSStyleRule * C;

    explicit CSSStyleRule(CSSOM_CSSStyleRule * impl);

    const char * selectorText() const;

    cssom::CSSStyleDeclaration style() const;
};



} // cssom

#endif // CSSOMPP_CSS_STYLE_RULE_HPP
