#ifndef CSSOMPP_CSS_STYLE_DECLARATION_HPP
#define CSSOMPP_CSS_STYLE_DECLARATION_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSStyleDeclaration.idl'
 */



#include <cssom/typedefs.h>

namespace cssom {



class CSSRule;



class CSSStyleDeclarationValue;



} // cssom

namespace cssom {



class CSSStyleDeclaration {
  public:
    typedef CSSOM_CSSStyleDeclaration * Impl;

    CSSStyleDeclaration();
    explicit CSSStyleDeclaration(cssom::CSSStyleDeclaration::Impl impl);
    CSSStyleDeclaration(const cssom::CSSStyleDeclaration &copy);
    ~CSSStyleDeclaration();

    cssom::CSSStyleDeclaration& operator=(const cssom::CSSStyleDeclaration &rhs);

    bool operator==(const cssom::CSSStyleDeclaration &rhs) const;

    bool isNull() const;

    void swap(cssom::CSSStyleDeclaration &rhs);

    const char * cssText() const;

    unsigned long length() const;

    const char * item(unsigned long index);

    const char * getPropertyValue(const char * property);

    const char * getPropertyPriority(const char * property);

    void setProperty(const char * property, const char * value);

    void setProperty(const char * property, const char * value, const char * priority);

    const char * removeProperty(const char * property);

    cssom::CSSStyleDeclarationValue values() const;

    cssom::CSSRule parentRule() const;

  protected:
    cssom::CSSStyleDeclaration::Impl _impl;
};



} // cssom

#endif // CSSOMPP_CSS_STYLE_DECLARATION_HPP
