#ifndef CSSOMPP_MEDIA_LIST_HPP
#define CSSOMPP_MEDIA_LIST_HPP



/**
 * WARNING: DO NOT EDIT!!!
 *
 * Generated by PyWIdl from 'CSSRule.idl'
 */



#include <cssom/typedefs.h>


namespace cssom {



class MediaList {
  public:
    typedef CSSOM_MediaList * C;

    MediaList();
    explicit MediaList(CSSOM_MediaList * impl);
    MediaList(const cssom::MediaList &copy);
    ~MediaList();

    cssom::MediaList& operator=(const cssom::MediaList &rhs);

    bool operator==(const cssom::MediaList &rhs) const;

    bool isNull() const;

    void swap(cssom::MediaList &rhs);

    operator const char *();

    const char * operator[](unsigned long index) const;

    const char * mediaText() const;
    void setMediaText(const char * mediaText);

    unsigned long length() const;

    const char * item(unsigned long index) const;

    void appendMedium(const char * medium);

    void deleteMedium(const char * medium);

  protected:
    CSSOM_MediaList * _impl;
};



} // cssom

#endif // CSSOMPP_MEDIA_LIST_HPP
