#include "CSSPropertySettings.h"

#include "CSSPropertyValue.h"
#include "CSSPropertyValue_azimuth.h"
#include "CSSPropertyValue_background.h"
#include "CSSPropertyValue_border.h"

#include <stddef.h>



const struct _CSSOM_CSSPropertyValue_settings CSSOM_propertySettings[] = {
  /* CSSOM_AZIMUTH_PROPERTY */
  { "azimuth",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_azimuth },
  /* CSSOM_BACKGROUND_PROPERTY */
  { "background",
    &CSSOM_CSSPropertyValue__genericShorthandEmit,
    CSSOM_CSSPropertyValue_backgroundSubtypes,
    _CSSOM_ASIZE(CSSOM_CSSPropertyValue_backgroundSubtypes),
    CSSOM_LexicalUnitRange_background },
  /* CSSOM_BACKGROUND_ATTACHMENT_PROPERTY */
  { "background-attachment",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_backgroundAttachment },
  /* CSSOM_BACKGROUND_COLOR_PROPERTY */
  { "background-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_backgroundColor },
  /* CSSOM_BACKGROUND_IMAGE_PROPERTY */
  { "background-image",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_backgroundImage },
  /* CSSOM_BACKGROUND_POSITION_PROPERTY */
  { "background-position",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_backgroundPosition },
  /* CSSOM_BACKGROUND_REPEAT_PROPERTY */
  { "background-repeat",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_backgroundRepeat },
  /* CSSOM_BORDER_PROPERTY */
  { "border",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_BORDER_COLLAPSE_PROPERTY */
  { "border-collapse",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderCollapse },
  /* CSSOM_BORDER_COLOR_PROPERTY */
  { "border-color",
    &CSSOM_CSSPropertyValue__boxShorthandEmit,
    CSSOM_CSSPropertyValue_borderColorSubtypes,
    _CSSOM_ASIZE(CSSOM_CSSPropertyValue_borderColorSubtypes),
    CSSOM_LexicalUnitRange_borderColor },
  /* CSSOM_BORDER_SPACING_PROPERTY */
  { "border-spacing",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderSpacing },
  /* CSSOM_BORDER_STYLE_PROPERTY */
  { "border-style",
    &CSSOM_CSSPropertyValue__boxShorthandEmit,
    CSSOM_CSSPropertyValue_borderStyleSubtypes,
    _CSSOM_ASIZE(CSSOM_CSSPropertyValue_borderStyleSubtypes),
    CSSOM_LexicalUnitRange_borderStyle },
  /* CSSOM_BORDER_TOP_PROPERTY */
  { "border-top",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_BORDER_RIGHT_PROPERTY */
  { "border-right",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_BORDER_BOTTOM_PROPERTY */
  { "border-bottom",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_BORDER_LEFT_PROPERTY */
  { "border-left",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_BORDER_TOP_COLOR_PROPERTY */
  { "border-top-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderTopColor },
  /* CSSOM_BORDER_RIGHT_COLOR_PROPERTY */
  { "border-right-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderRightColor },
  /* CSSOM_BORDER_BOTTOM_COLOR_PROPERTY */
  { "border-bottom-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderBottomColor },
  /* CSSOM_BORDER_LEFT_COLOR_PROPERTY */
  { "border-left-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderLeftColor },
  /* CSSOM_BORDER_TOP_STYLE_PROPERTY */
  { "border-top-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderTopStyle },
  /* CSSOM_BORDER_RIGHT_STYLE_PROPERTY */
  { "border-right-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderRightStyle },
  /* CSSOM_BORDER_BOTTOM_STYLE_PROPERTY */
  { "border-bottom-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderBottomStyle },
  /* CSSOM_BORDER_LEFT_STYLE_PROPERTY */
  { "border-left-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderLeftStyle },
  /* CSSOM_BORDER_TOP_WIDTH_PROPERTY */
  { "border-top-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderTopWidth },
  /* CSSOM_BORDER_RIGHT_WIDTH_PROPERTY */
  { "border-right-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderRightWidth },
  /* CSSOM_BORDER_BOTTOM_WIDTH_PROPERTY */
  { "border-bottom-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderBottomWidth },
  /* CSSOM_BORDER_LEFT_WIDTH_PROPERTY */
  { "border-left-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_borderLeftWidth },
  /* CSSOM_BORDER_WIDTH_PROPERTY */
  { "border-width",
    &CSSOM_CSSPropertyValue__boxShorthandEmit,
    CSSOM_CSSPropertyValue_borderWidthSubtypes,
    _CSSOM_ASIZE(CSSOM_CSSPropertyValue_borderWidthSubtypes),
    CSSOM_LexicalUnitRange_borderWidth },
  /* CSSOM_BOTTOM_PROPERTY */
  { "bottom",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CAPTION_SIDE_PROPERTY */
  { "caption-side",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CLEAR_PROPERTY */
  { "clear",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CLIP_PROPERTY */
  { "clip",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_COLOR_PROPERTY */
  { "color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CONTENT_PROPERTY */
  { "content",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_COUNTER_INCREMENT_PROPERTY */
  { "counter",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_COUNTER_RESET_PROPERTY */
  { "counter-reset",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CUE_PROPERTY */
  { "cue",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CUE_AFTER_PROPERTY */
  { "cue-after",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CUE_BEFORE_PROPERTY */
  { "cue-before",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_CURSOR_PROPERTY */
  { "cursor",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_DIRECTION_PROPERTY */
  { "direction",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_DISPLAY_PROPERTY */
  { "display",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_ELEVATION_PROPERTY */
  { "elevation",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_EMPTY_CELLS_PROPERTY */
  { "empty-cells",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FLOAT_PROPERTY */
  { "float",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_PROPERTY */
  { "font",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_FAMILY_PROPERTY */
  { "font-family",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_SIZE_PROPERTY */
  { "font-size",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_SIZE_ADJUST_PROPERTY */
  { "font-size-adjust",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_STRETCH_PROPERTY */
  { "font-stretch",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_STYLE_PROPERTY */
  { "font-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_VARIANT_PROPERTY */
  { "font-variant",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_FONT_WEIGHT_PROPERTY */
  { "font-weight",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_HEIGHT_PROPERTY */
  { "height",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LEFT_PROPERTY */
  { "left",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LETTER_SPACING_PROPERTY */
  { "letter-spacing",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LINE_HEIGHT_PROPERTY */
  { "line-height",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LIST_STYLE_PROPERTY */
  { "list-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LIST_STYLE_IMAGE_PROPERTY */
  { "list-style-image",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LIST_STYLE_POSITION_PROPERTY */
  { "list-style-position",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_LIST_STYLE_TYPE_PROPERTY */
  { "list-style-type",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARGIN_PROPERTY */
  { "margin",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARGIN_TOP_PROPERTY */
  { "margin-top",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARGIN_RIGHT_PROPERTY */
  { "margin-right",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARGIN_BOTTOM_PROPERTY */
  { "margin-bottom",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARGIN_LEFT_PROPERTY */
  { "margin-left",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARKER_OFFSET_PROPERTY */
  { "marker-offset",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MARKS_PROPERTY */
  { "marks",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MAX_HEIGHT_PROPERTY */
  { "max-height",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MAX_WIDTH_PROPERTY */
  { "max-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MIN_HEIGHT_PROPERTY */
  { "min-height",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_MIN_WIDTH_PROPERTY */
  { "min-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_ORPHANS_PROPERTY */
  { "orphans",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_OUTLINE_PROPERTY */
  { "outline",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_OUTLINE_COLOR_PROPERTY */
  { "outline-color",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_OUTLINE_STYLE_PROPERTY */
  { "outline-style",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_OUTLINE_WIDTH_PROPERTY */
  { "outline-width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_OVERFLOW_PROPERTY */
  { "overflow",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PADDING_PROPERTY */
  { "padding",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PADDING_TOP_PROPERTY */
  { "padding-top",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PADDING_RIGHT_PROPERTY */
  { "padding-right",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PADDING_BOTTOM_PROPERTY */
  { "padding-bottom",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PADDING_LEFT_PROPERTY */
  { "padding-left",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAGE_PROPERTY */
  { "page",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAGE_BREAK_AFTER_PROPERTY */
  { "page-break-after",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAGE_BREAK_BEFORE_PROPERTY */
  { "page-break-before",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAGE_BREAK_INSIDE_PROPERTY */
  { "page-break-inside",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAUSE_PROPERTY */
  { "pause",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAUSE_AFTER_PROPERTY */
  { "pause-after",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PAUSE_BEFORE_PROPERTY */
  { "pause-before",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PITCH_PROPERTY */
  { "pitch",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PITCH_RANGE_PROPERTY */
  { "pitch-range",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_PLAY_DURING_PROPERTY */
  { "play-during",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_POSITION_PROPERTY */
  { "position",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_QUOTES_PROPERTY */
  { "quotes",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_RICHNESS_PROPERTY */
  { "richness",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_RIGHT_PROPERTY */
  { "right",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SIZE_PROPERTY */
  { "size",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SPEAK_PROPERTY */
  { "speak",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SPEAK_HEADER_PROPERTY */
  { "speak-header",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SPEAK_NUMERAL_PROPERTY */
  { "speak-numeral",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SPEAK_PUNCTUATION_PROPERTY */
  { "speak-punctuation",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SPEECH_RATE_PROPERTY */
  { "speech-rate",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_SRC_PROPERTY */
  { "src",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_STRESS_PROPERTY */
  { "stress",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TABLE_LAYOUT_PROPERTY */
  { "table-layout",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TEXT_ALIGN_PROPERTY */
  { "text-align",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TEXT_DECORATION_PROPERTY */
  { "text-decoration",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TEXT_INDENT_PROPERTY */
  { "text-indent",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TEXT_SHADOW_PROPERTY */
  { "text-shadow",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TEXT_TRANSFORM_PROPERTY */
  { "text-transform",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_TOP_PROPERTY */
  { "top",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_UNICODE_BIDI_PROPERTY */
  { "unicode-bidi",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_VERTICAL_ALIGN_PROPERTY */
  { "vertical-align",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_VISIBILITY_PROPERTY */
  { "visibility",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_VOICE_FAMILY_PROPERTY */
  { "voice-family",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_VOLUME_PROPERTY */
  { "volume",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_WHITE_SPACE_PROPERTY */
  { "white-space",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_WIDOWS_PROPERTY */
  { "widows",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_WIDTH_PROPERTY */
  { "width",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_WORD_SPACING_PROPERTY */
  { "word-spacing",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever },
  /* CSSOM_Z_INDEX_PROPERTY */
  { "z-index",
    &CSSOM_CSSPropertyValue__genericEmit,
    NULL,
    0,
    CSSOM_LexicalUnitRange_whatever }
};




